export const SET_THEME = 'SET_THEME';
export const SET_TOGGLE_CHECKED = 'SET_TOGGLE_CHECKED';
export const GET_COLOR_BY_INDEX = 'GET_COLOR_BY_INDEX';
export const FETCH_ISSUES_INFO_FROM_REPO = 'FETCH_ISSUES_INFO_FROM_REPO';
export const FILTER_ISSUES = 'FILTER_ISSUES';
export const LOADING = 'LOADING';
export const ISSUE_TYPED = 'ISSUE_TYPED';
export const ISSUE_SELECTED = 'ISSUE_SELECTED';

export const GET_ISSUES_REPO = 'GET_ISSUES_REPO';
export const SET_ISSUES_TYPED = 'SET_ISSUES_TYPED';
export const FETCH_ISSUES_REJECTED = 'FETCH_ISSUES_REJECTED';
export const SET_ISSUE_SELECTED = 'SET_ISSUE_SELECTED';
export const GET_FIELTERED_ISSUES = 'GET_FIELTERED_ISSUES';
