export const SET_THEME = 'SET_THEME';
export const SET_TOGGLE_CHECKED = 'SET_TOGGLE_CHECKED';
export const GET_COLOR_BY_INDEX = 'GET_COLOR_BY_INDEX';

export const LOADING = 'LOADING';
export const ISSUE_TYPED = 'ISSUE_TYPED';
export const ISSUE_SELECTED = 'ISSUE_SELECTED';

export const GET_ISSUES = 'GET_ISSUES';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUES_REJECTED = 'FETCH_ISSUES_REJECTED';

export const SET_ISSUES_TYPED = 'SET_ISSUES_TYPED';
export const SET_ISSUE_SELECTED = 'SET_ISSUE_SELECTED';

export const FILTER_ISSUES = 'FILTER_ISSUES';
export const GET_FILTER_ISSUES = 'GET_FILTER_ISSUES';
